add GetDBByNameAndHostInfo() and GetDBsByHostInfo()
romberli/das pull request #118
Opened 2022-03-15 12:10 UTC by gengxiaoyun

add GetDBByNameAndHostInfo() and GetDBsByHostInfo()

2022-03-15 14:55 UTC, romberli requested changes

2022-03-15 14:55 UTC, romberli commented on internal/app/metadata/db_repository.go
> +		and db.db_name = ?
missed and ms.del_flag = 0

2022-03-15 14:55 UTC, romberli commented on internal/app/metadata/db_repository.go
> +		on db.cluster_id = ms.cluster_id
missed  and db.cluster_type = 1

2022-03-15 14:55 UTC, romberli commented on internal/app/metadata/db_repository.go
> +		and ms.host_ip = ?
missed and ms.del_flag = 0

2022-03-15 14:55 UTC, romberli commented on internal/app/metadata/db_repository.go
> +	dbInfoList := make([]*DBInfo, result.RowNumber())
make a []metadata.DB directly, doesn't need to make a []*DBInfo temporarily

2022-03-15 14:55 UTC, romberli commented on internal/app/metadata/db_repository.go
> +	dbList := make([]metadata.DB, result.RowNumber())
as making []metadata.DB directly, this line and following 3 lines doesn't need anymore

2022-03-16 03:59 UTC, gengxiaoyun commented on internal/app/metadata/db_repository.go
> +		and db.db_name = ?
done

2022-03-16 03:59 UTC, gengxiaoyun commented on internal/app/metadata/db_repository.go
> +		on db.cluster_id = ms.cluster_id
done

2022-03-16 04:00 UTC, gengxiaoyun commented on internal/app/metadata/db_repository.go
> +		on db.cluster_id = ms.cluster_id
done

2022-03-16 04:00 UTC, gengxiaoyun commented on internal/app/metadata/db_repository.go
> +		and ms.host_ip = ?
done

2022-03-16 04:00 UTC, gengxiaoyun commented on internal/app/metadata/db_repository.go
> +	dbInfoList := make([]*DBInfo, result.RowNumber())
done

2022-03-16 04:00 UTC, gengxiaoyun commented on internal/app/metadata/db_repository.go
> +	dbList := make([]metadata.DB, result.RowNumber())
done

2022-03-16 07:05 UTC, romberli approved these changes

2022-03-16 07:05 UTC, merged