alter metadata.user
romberli/das pull request #119
Opened 2022-03-15 13:28 UTC by AllinChen

2022-03-15 14:36 UTC, romberli commented on api/v1/metadata/user.go
>  // @Success 200 {string} string "{"mysql_clusters": [{"id": 1,"cluster_name": "mysql-cluster-pmm2","middleware_cluster_id": 0,"env_id": 1"monitor_system_id": 1,"del_flag": 0,"last_update_time": "2021
the return value should be middleware clusters

2022-03-15 14:36 UTC, romberli commented on api/v1/metadata/user.go
> +// @Router 	/api/v1/metadata/user/mysqlcluster/:id [get]
the path should be middleware-cluster

2022-03-15 14:36 UTC, romberli commented on internal/app/metadata/user_repository.go
> +	for row := 0; row < resultNum; row++ {
use constant.ZeroInt instead of 0

2022-03-15 14:36 UTC, romberli commented on pkg/message/metadata/user.go
> +	message.Messages[DebugMetadataGetMiddlewareClustersByUserID] = config.NewErrMessage(message.DefaultMessageHeader, DebugMetadataGetMiddlewareClustersByUserID, "metadata: get middlewarecluster list co
replace middlewarecluster with middleware cluster, same for the following mysqlcluster or mysqlserver

2022-03-15 14:36 UTC, romberli commented on pkg/message/metadata/user.go
> +	message.Messages[InfoMetadataGetAccountName] = config.NewErrMessage(message.DefaultMessageHeader, InfoMetadataGetAccountName, "metadata: get user by accountname completed. accountName: %s")
replace accountname with account name

2022-03-15 14:36 UTC, romberli commented on router/metadata.go
>  		metadataGroup.GET("/user/mysqlcluster/:id", metadata.GetMySQLClustersByUserID)
replace mysqlcluster with mysql-cluster

2022-03-16 02:09 UTC, AllinChen commented on api/v1/metadata/user.go
> +// @Summary get mysqlclusters by id
done

2022-03-16 02:09 UTC, AllinChen commented on api/v1/metadata/user.go
>  // @Success 200 {string} string "{"mysql_clusters": [{"id": 1,"cluster_name": "mysql-cluster-pmm2","middleware_cluster_id": 0,"env_id": 1"monitor_system_id": 1,"del_flag": 0,"last_update_time": "2021
done

2022-03-16 02:09 UTC, AllinChen commented on api/v1/metadata/user.go
> +// @Router 	/api/v1/metadata/user/mysqlcluster/:id [get]
done

2022-03-16 02:10 UTC, AllinChen commented on internal/app/metadata/user_repository.go
> +	for row := 0; row < resultNum; row++ {
done

2022-03-16 02:10 UTC, AllinChen commented on internal/app/metadata/user_repository_test.go
> +	asst.Nil(err, common.CombineMessageWithError("test GetByAccountNameOrEmployeeID failed", err))
done

2022-03-16 02:10 UTC, AllinChen commented on internal/app/metadata/user_repository_test.go
> +	asst.Equal(testUserAccountName, entity.GetAccountName(), "test GetByAccountNameOrEmployeeID failed")
done

2022-03-16 02:10 UTC, AllinChen commented on pkg/message/metadata/user.go
> +	message.Messages[DebugMetadataGetMiddlewareClustersByUserID] = config.NewErrMessage(message.DefaultMessageHeader, DebugMetadataGetMiddlewareClustersByUserID, "metadata: get middlewarecluster list co
done

2022-03-16 02:10 UTC, AllinChen commented on pkg/message/metadata/user.go
> +	message.Messages[InfoMetadataGetAccountName] = config.NewErrMessage(message.DefaultMessageHeader, InfoMetadataGetAccountName, "metadata: get user by accountname completed. accountName: %s")
done

2022-03-16 02:10 UTC, AllinChen commented on router/metadata.go
>  		metadataGroup.GET("/user/mysqlcluster/:id", metadata.GetMySQLClustersByUserID)
done

2022-03-16 06:56 UTC, romberli requested changes

2022-03-16 06:56 UTC, romberli commented on api/v1/metadata/user.go
> +// @Summary get all Mysql servers by id
use lower case of mysql

2022-03-16 07:07 UTC, AllinChen commented on api/v1/metadata/user.go
> +// @Summary get all Mysql servers by id
done

2022-03-16 07:08 UTC, romberli approved these changes

2022-03-16 07:08 UTC, merged