metadata.table模块完成
romberli/das pull request #122
Opened 2022-03-25 02:46 UTC by bluepongo

单元测试以及http测试已通过

2022-03-29 01:50 UTC, romberli requested changes

2022-03-31 08:45 UTC, SpicyChickenFLY commented on internal/app/metadata/table_entity.go
> +	// TableStatistics []metadata.TableStatistic `middleware:"table_statistics" json:"table_statistics"`
Done in [a8eef56](https://github.com/romberli/das/pull/122/commits/a8eef562a56b6e7109a0bdd21b762b049773da2e)

2022-03-31 08:45 UTC, SpicyChickenFLY commented on api/v1/metadata/table.go
> +// @Param	account_name	body string true "account name or employee id"
Done in [688e981](https://github.com/romberli/das/pull/122/commits/688e98135bf3dc4117cee11dc62fda19be9f21cd)

2022-03-31 08:46 UTC, SpicyChickenFLY commented on api/v1/metadata/table.go
> +	dbUser := global.DASMySQLPool.Config.DBUser
Done in [e457eb9](https://github.com/romberli/das/pull/122/commits/e457eb9cae2f114d1776dcab72119bac02a9939b)

2022-03-31 08:48 UTC, SpicyChickenFLY commented on api/v1/metadata/table.go
> +	dbPass := global.DASMySQLPool.Config.DBPass
Done in [e457eb9](https://github.com/romberli/das/pull/122/commits/e457eb9cae2f114d1776dcab72119bac02a9939b)

2022-03-31 08:48 UTC, SpicyChickenFLY commented on api/v1/metadata/table.go
> +	dbUser := global.DASMySQLPool.Config.DBUser
Done in [e457eb9](https://github.com/romberli/das/pull/122/commits/e457eb9cae2f114d1776dcab72119bac02a9939b)

2022-03-31 08:48 UTC, SpicyChickenFLY commented on api/v1/metadata/table.go
> +	tableName := tableNameInterface.(string)
changed to ShouldBindJSON in [f1e59f4](https://github.com/romberli/das/pull/122/commits/f1e59f452334e0ffbed94c78015a8ff76a6c9152)

2022-04-02 06:12 UTC, merged